version: '3.8'

services:
  frontend:
    build:
      context: ../website
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../backend/.env
    restart: unless-stopped
    volumes:
      - backend_logs:/usr/src/app/logs

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  backend_logs:
